### ISSUE TITLE
Support for master/slave pod cluster

### ISSUE THREAD

**Issue by stphung** [autodesk-cloud/ochopod#1]
It looks like it is possible to know whether a pod is a follower or a leader once it is running. Is it possible to know this information inside of the configure method in pod.py?

I was thinking of a general use case where you could run a pod cluster with one pod acting as the master and the others acting as the slaves but that would require knowing this before starting the application.

**Comment by opaugam** [comment]
Good question. The follower/leader mechanism is strictly related to how ochopod manages its clustering and has no real meaning for what you run underneath, unless I guess you wish to use that mechanism somehow to implement a (coarse) leader election for free.

I can add it this week if you need it.
