### ISSUE TITLE
Ability to leave managed process running

### ISSUE THREAD

**Issue by stphung** [autodesk-cloud/ochopod#14]
I tried overriding the tear_down implementation to be empty such as:

```
def tear_down(self, process):
  pass
```

This results in the ochopod configuration blocking however and still waiting for the process to be eventually terminated by the system after about 1 minute. It would be awesome if I could leave the existing process running so that I can have more control on the next configuration run.

My use case is zero downtime haproxy configuration reloads. I basically need to have the process running so I can start a new haproxy process which can signal to the currently running process.

**Comment by opaugam** [comment]
ok - simply define 'soft=True' in your pod.py strategy and ochopod will not attempt to force a SIGKILL should your tear_down() implementation be a no-op.
