### ISSUE TITLE
curl -XPOST http://127.0.0.1:8080/control/ANYTHING bad answer

### ISSUE THREAD

**Issue by titilambert** [autodesk-cloud/ochopod#27]
Hi !
`curl -XPOST http://127.0.0.1:8080/control/ANYTHING` take a long while to answer `{}`
I will try to fix it.

**Comment by opaugam** [comment]
sorry - what's the context?

**Comment by titilambert** [comment]
You're right, I didn't explain the context :/
I just launch an ochopod instance an try to request it with the following request:
`curl -XPOST http://127.0.0.1:8080/control/ANYTHING`
It take a long long while before getting an (empty) answer. (I get `{}`)
May we have to get a 404 error ? Because `ANYTHING` does not exist (see: http://autodesk-cloud.github.io/ochopod/concepts.html#registration)

**Comment by opaugam** [comment]
pod 1.0.7 updated (finally)
