### ISSUE TITLE
thiner base docker image

### ISSUE THREAD

**Issue by UncleBarney** [autodesk-cloud/ochopod#38]
Currently we are using ubuntu 14.04 as base image, which is quite heavy, which resulting in huge image size for down-stream pod images. For example our auxiliary images' average size is around 500MB.

Do you think it's a good idea to go with something lighter and cut down the base ochopod image size?

**Comment by opaugam** [comment]
mh is that right ? look at the size of the flask sample image .. is that equally large ?

**Comment by UncleBarney** [comment]
sorry, my bad, didn't see the replication images and flask sample image. Looks like the ochopod base image is around 100MB in size.
